### PR TITLE
YEEEEEEEEEEEEEEEET

### PR DESCRIPTION
**Pull request by li223**
General Changes
~~Updated to .Net Core 3.0~~ 😒
Updated EFCore Package Versions
Some Cleanup - Just removed unecessary using directives
Basically just did what VS told me to do

Api Changes
`/api/thread/post?thread=[thread]` is now `/api/thread/posts?id=[id]`
Added `/api/thread/single?id=[id]`
`/api/thread/create` now returns the created thread
Commentted out all of ValuesController as it creates dead endpoints

Setup Changes
Added `ServerConfig.json` file to enable customisation of database providers amongst other things
Added `ServerConfig.cs` file
When creating a new DB in Startup Ctor, the parameters will now be filled using the deserialized json file
Added PostgreSql and Sqlite support
Added `EnableEndpointRouting = false` to stop VS crying at me

### CODE REVIEW

**Comment by Naamloos** [comment]
Will merge after confirmed safe

**Comment by Naamloos** [comment]
.net core is still in pre-release so I'd prefer you take it back to 2.x

**Comment by li223** [comment]
Many many package conflicts. Closing PR until I fix them.

**Comment by Naamloos** [comment]
oki oki checking at home

**Pull request merged**
